/* 
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Other/SQLTemplate.sql to edit this template
 */
/**
 * Author:  Sudip
 * Created: 10-Nov-2023
 */

-- Sql Query to create notes db
CREATE TABLE notes (
    note_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    note_heading VARCHAR2(255),
    content TEXT,
    user_email VARCHAR2(255),
    FOREIGN KEY (user_email) REFERENCES users(email)
);

-- Sql to insert note
INSERT INTO notes (note_heading, content, user_email) VALUES ('Meeting Agenda', 'Discuss project updates and timelines.', 'xeon550@gmail.com');